sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm run test -- --coverage

after_success:
  - docker build -t tkdinh/fib-client ./client
  - docker build -t tkdinh/fib-nginx ./nginx
  - docker build -t tkdinh/fib-server ./server
  - docker build -t tkdinh/fib-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take the images and push to docker hub
  - docker push tkdinh/fib-client
  - docker push tkdinh/fib-nginx
  - docker push tkdinh/fib-server
  - docker push tkdinh/fib-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fib"
  env: "Fib-env"
  bucket_name: "elasticbeanstalk-us-east-1-266891367692"
  bucket_path: "fib"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
